const case1 = {
  inputData: {
    id: 'getBySnUsingPOST_2',
    path: '/auth/template/ReceivingDocuments/getBySn/{type}/{templateSn}',
    title: '根据模板编码获取对应的模板信息',
    method: 'post',
    query: [
      {
        name: 'templateSn',
        description: '模板编码',
        required: true,
        type: 'string',
        subType: null,
        properties: null,
      },
      {
        name: 'type',
        description: '模板类型： 1_收文模板；2_发文模板',
        required: true,
        type: 'integer',
        subType: null,
        properties: null,
      },
    ],
    body: null,
    response: [
      {
        name: 'code',
        description: '业务响应状态码',
        required: false,
        type: 'integer',
        subType: null,
        properties: null,
      },
      {
        name: 'data',
        description: '业务响应数据',
        required: false,
        subTypes: null,
        properties: [
          {
            name: 'templateName',
            description: '模板名称',
            required: false,
            type: 'string',
            subType: null,
            properties: null,
          },
          {
            name: 'buttonInfo',
            description: '按钮信息',
            required: false,
            subTypes: null,
            properties: [
              {
                name: 'name',
                description: '用户/部门名称',
                required: false,
                type: 'string',
                subType: null,
                properties: null,
              },
              {
                name: 'id',
                description: '用户/部门ID',
                required: false,
                type: 'integer',
                subType: null,
                properties: null,
              },
            ],
          },
          {
            name: 'id',
            description: '模板ID',
            required: false,
            type: 'integer',
            subType: null,
            properties: null,
          },
          {
            name: 'templateSn',
            description: '模板编码',
            required: false,
            type: 'string',
            subType: null,
            properties: null,
          },
          {
            name: 'content',
            description: '稿纸',
            required: false,
            type: 'string',
            subType: null,
            properties: null,
          },
          {
            name: 'contentExtendJson',
            description: '稿纸内容附加信息json',
            required: false,
            type: 'string',
            subType: null,
            properties: null,
          },
          {
            name: 'nodeInfoList',
            description: '流程信息',
            required: false,
            type: 'array',
            subTypes: null,
            properties: [
              {
                name: 'nodeName',
                description: '流程节点名称',
                required: false,
                type: 'string',
                subType: null,
                properties: null,
              },
              {
                name: 'approveType',
                description: '审批方式：1_依次审批  2_会签  3_或签',
                required: false,
                type: 'integer',
                subType: null,
                properties: null,
              },
              {
                name: 'sysId',
                description: '系统ID',
                required: false,
                type: 'integer',
                subType: null,
                properties: null,
              },
              {
                name: 'nodeUserList',
                required: false,
                type: 'array',
                subTypes: null,
                properties: [
                  {
                    name: 'carbonCopyList',
                    required: false,
                    type: 'array',
                    subTypes: null,
                    properties: [
                      {
                        name: 'sysId',
                        description: '系统ID',
                        required: false,
                        type: 'integer',
                        subType: null,
                        properties: null,
                      },
                      {
                        name: 'isRead',
                        description: '是否已读（0 未读  1已读）',
                        required: false,
                        type: 'boolean',
                        subType: null,
                        properties: null,
                      },
                      {
                        name: 'userName',
                        description: '被抄送人姓名',
                        required: false,
                        type: 'string',
                        subType: null,
                        properties: null,
                      },
                      {
                        name: 'createdOn',
                        required: false,
                        type: 'string',
                        subType: null,
                        properties: null,
                      },
                      {
                        name: 'userId',
                        description: '被抄送人userId',
                        required: false,
                        type: 'integer',
                        subType: null,
                        properties: null,
                      },
                      {
                        name: 'orgId',
                        description: '租户id',
                        required: false,
                        type: 'integer',
                        subType: null,
                        properties: null,
                      },
                      {
                        name: 'approveUserId',
                        description: '流程节点ID',
                        required: false,
                        type: 'integer',
                        subType: null,
                        properties: null,
                      },
                      {
                        name: 'modifiedOn',
                        required: false,
                        type: 'string',
                        subType: null,
                        properties: null,
                      },
                      {
                        name: 'instanceId',
                        description: '流程节点ID',
                        required: false,
                        type: 'integer',
                        subType: null,
                        properties: null,
                      },
                      {
                        name: 'isDeleted',
                        required: false,
                        type: 'boolean',
                        subType: null,
                        properties: null,
                      },
                      {
                        name: 'createdBy',
                        required: false,
                        type: 'integer',
                        subType: null,
                        properties: null,
                      },
                      {
                        name: 'modifiedBy',
                        required: false,
                        type: 'integer',
                        subType: null,
                        properties: null,
                      },
                      {
                        name: 'id',
                        required: false,
                        type: 'integer',
                        subType: null,
                        properties: null,
                      },
                    ],
                  },
                  {
                    name: 'sysId',
                    description: '系统ID',
                    required: false,
                    type: 'integer',
                    subType: null,
                    properties: null,
                  },
                  {
                    name: 'operationState',
                    description:
                      '操作状态（9:待阅，10:已阅，6:无需处理，1：待审批，2：退回，3：作废，4：撤销，5：归档）',
                    required: false,
                    type: 'integer',
                    subType: null,
                    properties: null,
                  },
                  {
                    name: 'approveLogList',
                    required: false,
                    type: 'array',
                    subTypes: null,
                    properties: [
                      {
                        name: 'modifiedOn',
                        required: false,
                        type: 'string',
                        subType: null,
                        properties: null,
                      },
                      {
                        name: 'isDeleted',
                        required: false,
                        type: 'boolean',
                        subType: null,
                        properties: null,
                      },
                      {
                        name: 'createdBy',
                        required: false,
                        type: 'integer',
                        subType: null,
                        properties: null,
                      },
                      {
                        name: 'operationState',
                        description:
                          '操作状态（无需处理，待处理，已审批/提交，退回，作废，撤销）',
                        required: false,
                        type: 'integer',
                        subType: null,
                        properties: null,
                      },
                      {
                        name: 'modifiedBy',
                        required: false,
                        type: 'integer',
                        subType: null,
                        properties: null,
                      },
                      {
                        name: 'id',
                        required: false,
                        type: 'integer',
                        subType: null,
                        properties: null,
                      },
                      {
                        name: 'createdOn',
                        required: false,
                        type: 'string',
                        subType: null,
                        properties: null,
                      },
                      {
                        name: 'approveOption',
                        description: '审批意见',
                        required: false,
                        type: 'string',
                        subType: null,
                        properties: null,
                      },
                      {
                        name: 'approveUserId',
                        description: '节点人员ID',
                        required: false,
                        type: 'integer',
                        subType: null,
                        properties: null,
                      },
                    ],
                  },
                  {
                    name: 'userName',
                    description: '审批人姓名',
                    required: false,
                    type: 'string',
                    subType: null,
                    properties: null,
                  },
                  {
                    name: 'createdOn',
                    required: false,
                    type: 'string',
                    subType: null,
                    properties: null,
                  },
                  {
                    name: 'userId',
                    description: '审批人userId',
                    required: false,
                    type: 'integer',
                    subType: null,
                    properties: null,
                  },
                  {
                    name: 'orgId',
                    description: '租户id',
                    required: false,
                    type: 'integer',
                    subType: null,
                    properties: null,
                  },
                  {
                    name: 'modifiedOn',
                    required: false,
                    type: 'string',
                    subType: null,
                    properties: null,
                  },
                  {
                    name: 'isDeleted',
                    required: false,
                    type: 'boolean',
                    subType: null,
                    properties: null,
                  },
                  {
                    name: 'createdBy',
                    required: false,
                    type: 'integer',
                    subType: null,
                    properties: null,
                  },
                  {
                    name: 'modifiedBy',
                    required: false,
                    type: 'integer',
                    subType: null,
                    properties: null,
                  },
                  {
                    name: 'id',
                    required: false,
                    type: 'integer',
                    subType: null,
                    properties: null,
                  },
                  {
                    name: 'processNodeId',
                    description: '流程节点ID',
                    required: false,
                    type: 'integer',
                    subType: null,
                    properties: null,
                  },
                ],
              },
              {
                name: 'nodeType',
                description: '节点类型： 1_正常，2_分发',
                required: false,
                type: 'integer',
                subType: null,
                properties: null,
              },
              {
                name: 'type',
                required: false,
                type: 'integer',
                subType: null,
                properties: null,
              },
              {
                name: 'createdOn',
                required: false,
                type: 'string',
                subType: null,
                properties: null,
              },
              {
                name: 'orgId',
                description: '租户ID',
                required: false,
                type: 'integer',
                subType: null,
                properties: null,
              },
              {
                name: 'current',
                required: false,
                type: 'boolean',
                subType: null,
                properties: null,
              },
              {
                name: 'modifiedOn',
                required: false,
                type: 'string',
                subType: null,
                properties: null,
              },
              {
                name: 'instanceId',
                description: '流程实例id',
                required: false,
                type: 'integer',
                subType: null,
                properties: null,
              },
              {
                name: 'isDeleted',
                required: false,
                type: 'boolean',
                subType: null,
                properties: null,
              },
              {
                name: 'createdBy',
                required: false,
                type: 'integer',
                subType: null,
                properties: null,
              },
              {
                name: 'hasConfigAssigness',
                required: false,
                type: 'boolean',
                subType: null,
                properties: null,
              },
              {
                name: 'modifiedBy',
                required: false,
                type: 'integer',
                subType: null,
                properties: null,
              },
              {
                name: 'specialMark',
                description: '特殊节点标识： 0_非特殊（默认）  1_套红  2_盖章',
                required: false,
                type: 'string',
                subType: null,
                properties: null,
              },
              {
                name: 'id',
                required: false,
                type: 'integer',
                subType: null,
                properties: null,
              },
              {
                name: 'nodeId',
                description: '流程节点ID',
                required: false,
                type: 'string',
                subType: null,
                properties: null,
              },
              {
                name: 'allowMultiplePeople',
                required: false,
                type: 'boolean',
                subType: null,
                properties: null,
              },
              {
                name: 'approveState',
                description:
                  '审批状态 1：待审批，2：退回，3：作废，4：撤销，5：归档',
                required: false,
                type: 'integer',
                subType: null,
                properties: null,
              },
            ],
          },
          {
            name: 'wfType',
            description: '工作流类型',
            required: false,
            type: 'string',
            subType: null,
            properties: null,
          },
        ],
      },
      {
        name: 'success',
        description: '业务响应是否成功',
        required: false,
        type: 'boolean',
        subType: null,
        properties: null,
      },
      {
        name: 'message',
        description: '业务响应信息',
        required: false,
        type: 'string',
        subType: null,
        properties: null,
      },
    ],
    tags: ['V1.0.0-收发文模板', '收发文模板'],
  },
  config: { comment: true, tsNotStrict: true },
  expectResult: {
    code: '{\n' +
      '/** 业务响应状态码 */\n' +
      'code: number,\n' +
      '/** 业务响应数据 */\n' +
      'data: DataVO,\n' +
      '/** 业务响应是否成功 */\n' +
      'success: boolean,\n' +
      '/** 业务响应信息 */\n' +
      'message: string,\n' +
      '}',
    models: [
      {
        name: 'DataVO',
        value: {
          templateName: 'string&_$_$_&模板名称',
          buttonInfo: 'ButtonInfoVO&_$_$_&按钮信息',
          id: 'number&_$_$_&模板ID',
          templateSn: 'string&_$_$_&模板编码',
          content: 'string&_$_$_&稿纸',
          contentExtendJson: 'string&_$_$_&稿纸内容附加信息json',
          nodeInfoList: 'Array<NodeInfoListVO>&_$_$_&流程信息',
          wfType: 'string&_$_$_&工作流类型',
        },
      },
      {
        name: 'ButtonInfoVO',
        value: { name: 'string&_$_$_&用户/部门名称', id: 'number&_$_$_&用户/部门ID' },
      },
      {
        name: 'NodeInfoListVO',
        value: {
          nodeName: 'string&_$_$_&流程节点名称',
          approveType: 'number&_$_$_&审批方式：1_依次审批  2_会签  3_或签',
          sysId: 'number&_$_$_&系统ID',
          nodeUserList: 'Array<NodeUserListVO>',
          nodeType: 'number&_$_$_&节点类型： 1_正常，2_分发',
          type: 'number',
          createdOn: 'string',
          orgId: 'number&_$_$_&租户ID',
          current: 'boolean',
          modifiedOn: 'string',
          instanceId: 'number&_$_$_&流程实例id',
          isDeleted: 'boolean',
          createdBy: 'number',
          hasConfigAssigness: 'boolean',
          modifiedBy: 'number',
          specialMark: 'string&_$_$_&特殊节点标识： 0_非特殊（默认）  1_套红  2_盖章',
          id: 'number',
          nodeId: 'string&_$_$_&流程节点ID',
          allowMultiplePeople: 'boolean',
          approveState: 'number&_$_$_&审批状态 1：待审批，2：退回，3：作废，4：撤销，5：归档',
        },
      },
      {
        name: 'NodeUserListVO',
        value: {
          carbonCopyList: 'Array<CarbonCopyListVO>',
          sysId: 'number&_$_$_&系统ID',
          operationState: 'number&_$_$_&操作状态（9:待阅，10:已阅，6:无需处理，1：待审批，2：退回，3：作废，4：撤销，5：归档）',
          approveLogList: 'Array<ApproveLogListVO>',
          userName: 'string&_$_$_&审批人姓名',
          createdOn: 'string',
          userId: 'number&_$_$_&审批人userId',
          orgId: 'number&_$_$_&租户id',
          modifiedOn: 'string',
          isDeleted: 'boolean',
          createdBy: 'number',
          modifiedBy: 'number',
          id: 'number',
          processNodeId: 'number&_$_$_&流程节点ID',
        },
      },
      {
        name: 'CarbonCopyListVO',
        value: {
          sysId: 'number&_$_$_&系统ID',
          isRead: 'boolean&_$_$_&是否已读（0 未读  1已读）',
          userName: 'string&_$_$_&被抄送人姓名',
          createdOn: 'string',
          userId: 'number&_$_$_&被抄送人userId',
          orgId: 'number&_$_$_&租户id',
          approveUserId: 'number&_$_$_&流程节点ID',
          modifiedOn: 'string',
          instanceId: 'number&_$_$_&流程节点ID',
          isDeleted: 'boolean',
          createdBy: 'number',
          modifiedBy: 'number',
          id: 'number',
        },
      },
      {
        name: 'ApproveLogListVO',
        value: {
          modifiedOn: 'string',
          isDeleted: 'boolean',
          createdBy: 'number',
          operationState: 'number&_$_$_&操作状态（无需处理，待处理，已审批/提交，退回，作废，撤销）',
          modifiedBy: 'number',
          id: 'number',
          createdOn: 'string',
          approveOption: 'string&_$_$_&审批意见',
          approveUserId: 'number&_$_$_&节点人员ID',
        },
      },
    ]
    ,
  },
};

const case2 = {
  inputData: {
    id: 'getReadPageListForAppUsingGET',
    path: '/auth/m/myOfficialDocument/getReadPageList',
    title: '已阅公文列表（分页）（app端接口）',
    method: 'get',
    query: [
      {
        name: 'curPage',
        description: '当前页',
        required: true,
        type: 'integer',
        subType: null,
        properties: null,
      },
      {
        name: 'keyWord',
        description: '关键字查询（app端查询：公文标题、文号、提交人）',
        required: false,
        type: 'string',
        subType: null,
        properties: null,
      },
      {
        name: 'pageSize',
        description: '每页条数',
        required: true,
        type: 'integer',
        subType: null,
        properties: null,
      },
    ],
    body: null,
    response: [
      {
        name: '',
        description: '业务响应数据',
        required: false,
        subTypes: null,
        properties: [
          {
            name: 'current',
            required: false,
            type: 'integer',
            subType: null,
            properties: null,
          },
          {
            name: 'total',
            required: false,
            type: 'integer',
            subType: null,
            properties: null,
          },
          {
            name: 'pages',
            required: false,
            type: 'integer',
            subType: null,
            properties: null,
          },
          {
            name: 'size',
            required: false,
            type: 'integer',
            subType: null,
            properties: null,
          },
          {
            name: 'records',
            required: false,
            type: 'array',
            subTypes: null,
            properties: [
              {
                name: 'urgencyId',
                description: '紧急程度id',
                required: false,
                type: 'integer',
                subType: null,
                properties: null,
              },
              {
                name: 'odTypeName',
                description: '公文类型名称',
                required: false,
                type: 'string',
                subType: null,
                properties: null,
              },
              {
                name: 'restrictedDate',
                description: '限办日期 我的待办列表才会用到，其他用不到',
                required: false,
                type: 'string',
                subType: null,
                properties: null,
              },
              {
                name: 'documentNumber',
                description: '文号',
                required: false,
                type: 'string',
                subType: null,
                properties: null,
              },
              {
                name: 'wfUserNames',
                description: '当前审批节点对应的待审批人员姓名',
                required: false,
                type: 'array',
                subType: 'string',
                properties: null,
              },
              {
                name: 'title',
                description: '公文标题',
                required: false,
                type: 'string',
                subType: null,
                properties: null,
              },
              {
                name: 'createdOn',
                description: '创建时间',
                required: false,
                type: 'string',
                subType: null,
                properties: null,
              },
              {
                name: 'urgency',
                description: '紧急程度',
                required: false,
                type: 'string',
                subType: null,
                properties: null,
              },
              {
                name: 'wfState',
                description:
                  '工作流状态 1_审批中；2_已回退；3_已撤回；4_已办结；5_已作废',
                required: false,
                type: 'integer',
                subType: null,
                properties: null,
              },
              {
                name: 'createdName',
                description: '创建人',
                required: false,
                type: 'string',
                subType: null,
                properties: null,
              },
              {
                name: 'id',
                description: '公文id',
                required: false,
                type: 'integer',
                subType: null,
                properties: null,
              },
              {
                name: 'wfMemo',
                description: '审批状态',
                required: false,
                type: 'string',
                subType: null,
                properties: null,
              },
              {
                name: 'odType',
                description: '公文类型',
                required: false,
                type: 'integer',
                subType: null,
                properties: null,
              },
            ],
          },
        ],
      },
    ],
    tags: ['V1.0.0-公文中心、流转', '公文中心、流转'],
  },
  config: { comment: false, tsNotStrict: false },
  expectResult: {
    code: '{current?:number,total?:number,pages?:number,size?:number,records?:Array<RecordsVO>}',
    models: [
      {
        name: 'RecordsVO',
        value: {
          'urgencyId?': 'number',
          'odTypeName?': 'string',
          'restrictedDate?': 'string',
          'documentNumber?': 'string',
          'wfUserNames?': 'Array<string>',
          'title?': 'string',
          'createdOn?': 'string',
          'urgency?': 'string',
          'wfState?': 'number',
          'createdName?': 'string',
          'id?': 'number',
          'wfMemo?': 'string',
          'odType?': 'number',
        },
      },
    ],
  },
};

const case3 = {
  inputData: {
    id: 'editUsingPOST',
    path: '/auth/baseConfig/edit',
    title: '编辑',
    method: 'post',
    query: null,
    body: [
      {
        name: 'configName',
        description: '名称',
        required: false,
        type: 'string',
        subType: null,
        properties: null,
      },
      {
        name: 'descriptionContent',
        description: '描述',
        required: false,
        type: 'string',
        subType: null,
        properties: null,
      },
      {
        name: 'dataType',
        description:
          '数据分类：1_收文类型；2_文件类型；3_公文文种；4_保密等级；5_紧急程度；6_单位分类；7_机构分组；8_去向选择；9_机构代字；10_归档年限；11_媒体类别；12_公开方式',
        required: false,
        type: 'integer',
        subType: null,
        properties: null,
      },
      {
        name: 'id',
        description: 'id',
        required: false,
        type: 'integer',
        subType: null,
        properties: null,
      },
      {
        name: 'sort',
        description: '排序',
        required: false,
        type: 'integer',
        subType: null,
        properties: null,
      },
    ],
    response: [
      {
        name: '',
        description: '业务响应数据',
        required: false,
        type: 'boolean',
        subType: null,
        properties: null,
      },
    ],
    tags: ['V2.0.0-基础设置', '基础设置'],
    headersJson: 'application/json; charset=utf-8',
  },
  config: { comment: true, tsNotStrict: true },
  expectResult: {
    code: 'boolean',
    models: [],
  },
};

const case4 = {
  inputData: {
    id: 'queryDptListByKeywordUsingGET',
    path: '/auth/m/user/queryDptListByKeyword',
    title: '模糊查询部门名称',
    method: 'get',
    query: [
      {
        name: 'keyword',
        description: '模糊查询关键字',
        required: true,
        type: 'string',
        subType: null,
        properties: null,
      },
    ],
    body: null,
    response: [
      {
        name: '',
        description: '业务响应数据',
        required: false,
        type: 'array',
        subTypes: null,
        properties: [
          {
            name: 'departmentName',
            description: '部门名称',
            required: false,
            type: 'string',
            subType: null,
            properties: null,
          },
          {
            name: 'departmentId',
            description: '部门ID',
            required: false,
            type: 'integer',
            subType: null,
            properties: null,
          },
        ],
      },
    ],
    tags: ['用户信息'],
  },
  config: { comment: false, tsNotStrict: false },
  expectResult: {
    code: 'Array<AnonymousDto>',
    models: [
      {
        name: 'AnonymousDto',
        value: { 'departmentName?': 'string', 'departmentId?': 'number' },
      },
    ],
  },
};

// 模拟循环引用
const case5 = {
  inputData: {
    id: 'getUserInfoUsingGET',
    path: '/auth/m/user/getUserInfo',
    title: '获取用户信息',
    method: 'get',
    query: null,
    body: null,
    response: [
      {
        name: 'code',
        description: '业务响应状态码',
        required: false,
        type: 'integer',
        subType: null,
        properties: null,
      },
      {
        name: 'data',
        description: '业务响应数据',
        required: false,
        subTypes: null,
        properties: [
          {
            name: 'deviceType',
            description: '设备类型',
            required: false,
            type: 'integer',
            subType: null,
            properties: null,
          },
          {
            name: 'orgDptInfoList',
            description: '父级部门ID',
            required: false,
            type: 'array',
            subTypes: null,
            properties: [],
          },
          {
            name: 'orgName',
            description: '机构名称',
            required: false,
            type: 'string',
            subType: null,
            properties: null,
          },
          {
            name: 'dptId',
            description: '部门ID',
            required: false,
            type: 'integer',
            subType: null,
            properties: null,
          },
          {
            name: 'dptName',
            description: '部门名称',
            required: false,
            type: 'string',
            subType: null,
            properties: null,
          },
          {
            name: 'loginName',
            description: '乐号',
            required: false,
            type: 'string',
            subType: null,
            properties: null,
          },
          {
            name: 'photo',
            description: '头像url',
            required: false,
            type: 'string',
            subType: null,
            properties: null,
          },
          {
            name: 'userId',
            description: '用户ID',
            required: false,
            type: 'integer',
            subType: null,
            properties: null,
          },
          {
            name: 'orgId',
            description: '机构ID',
            required: false,
            type: 'integer',
            subType: null,
            properties: null,
          },
          {
            name: 'permissionInfo',
            description: '权限列表（包含按钮）',
            required: false,
            subTypes: null,
            properties: [
              {
                name: 'menuList',
                description: '功能菜单列表',
                required: false,
                type: 'array',
                subTypes: null,
                properties: [
                  {
                    name: 'hideInMenu',
                    description: '菜单是否隐藏',
                    required: false,
                    type: 'boolean',
                    subType: null,
                    properties: null,
                  },
                  {
                    name: 'permissionType',
                    description: '类型 1：菜单 2：按钮',
                    required: false,
                    type: 'integer',
                    subType: null,
                    properties: null,
                  },
                  {
                    name: 'subMenuList',
                    description: '子菜单列表',
                    required: false,
                    type: 'array',
                    subTypes: null,
                    properties: [
                      {
                        name: 'hideInMenu',
                        description: '菜单是否隐藏',
                        required: false,
                        type: 'boolean',
                        subType: null,
                        properties: null,
                      },
                      {
                        name: 'permissionType',
                        description: '类型 1：菜单 2：按钮',
                        required: false,
                        type: 'integer',
                        subType: null,
                        properties: null,
                      },
                      {
                        name: 'subMenuList',
                        description: '子菜单列表',
                        required: false,
                        type: 'array',
                        subTypes: null,
                        properties: [
                          {
                            name: 'hideInMenu',
                            description: '菜单是否隐藏',
                            required: false,
                            type: 'boolean',
                            subType: null,
                            properties: null,
                          },
                          {
                            name: 'permissionType',
                            description: '类型 1：菜单 2：按钮',
                            required: false,
                            type: 'integer',
                            subType: null,
                            properties: null,
                          },
                          {
                            name: 'componentPath',
                            description: '菜单路由',
                            required: false,
                            type: 'string',
                            subType: null,
                            properties: null,
                          },
                          {
                            name: 'perms',
                            description: '权限标识',
                            required: false,
                            type: 'string',
                            subType: null,
                            properties: null,
                          },
                          {
                            name: 'id',
                            description: '菜单ID',
                            required: false,
                            type: 'integer',
                            subType: null,
                            properties: null,
                          },
                          {
                            name: 'extraAttrs',
                            description: '扩展属性列表',
                            required: false,
                            type: 'string',
                            subType: null,
                            properties: null,
                          },
                          {
                            name: 'isDisplay',
                            description: '是否显示 0不显示 1显示',
                            required: false,
                            type: 'boolean',
                            subType: null,
                            properties: null,
                          },
                          {
                            name: 'parentId',
                            description: '父级菜单ID',
                            required: false,
                            type: 'integer',
                            subType: null,
                            properties: null,
                          },
                          {
                            name: 'seq',
                            description: '菜单排序',
                            required: false,
                            type: 'integer',
                            subType: null,
                            properties: null,
                          },
                          {
                            name: 'permissionName',
                            description: '菜单标题',
                            required: false,
                            type: 'string',
                            subType: null,
                            properties: null,
                          },
                        ],
                      },
                      {
                        name: 'componentPath',
                        description: '菜单路由',
                        required: false,
                        type: 'string',
                        subType: null,
                        properties: null,
                      },
                      {
                        name: 'perms',
                        description: '权限标识',
                        required: false,
                        type: 'string',
                        subType: null,
                        properties: null,
                      },
                      {
                        name: 'id',
                        description: '菜单ID',
                        required: false,
                        type: 'integer',
                        subType: null,
                        properties: null,
                      },
                      {
                        name: 'extraAttrs',
                        description: '扩展属性列表',
                        required: false,
                        type: 'string',
                        subType: null,
                        properties: null,
                      },
                      {
                        name: 'isDisplay',
                        description: '是否显示 0不显示 1显示',
                        required: false,
                        type: 'boolean',
                        subType: null,
                        properties: null,
                      },
                      {
                        name: 'parentId',
                        description: '父级菜单ID',
                        required: false,
                        type: 'integer',
                        subType: null,
                        properties: null,
                      },
                      {
                        name: 'seq',
                        description: '菜单排序',
                        required: false,
                        type: 'integer',
                        subType: null,
                        properties: null,
                      },
                      {
                        name: 'permissionName',
                        description: '菜单标题',
                        required: false,
                        type: 'string',
                        subType: null,
                        properties: null,
                      },
                    ],
                  },
                  {
                    name: 'componentPath',
                    description: '菜单路由',
                    required: false,
                    type: 'string',
                    subType: null,
                    properties: null,
                  },
                  {
                    name: 'perms',
                    description: '权限标识',
                    required: false,
                    type: 'string',
                    subType: null,
                    properties: null,
                  },
                  {
                    name: 'id',
                    description: '菜单ID',
                    required: false,
                    type: 'integer',
                    subType: null,
                    properties: null,
                  },
                  {
                    name: 'extraAttrs',
                    description: '扩展属性列表',
                    required: false,
                    type: 'string',
                    subType: null,
                    properties: null,
                  },
                  {
                    name: 'isDisplay',
                    description: '是否显示 0不显示 1显示',
                    required: false,
                    type: 'boolean',
                    subType: null,
                    properties: null,
                  },
                  {
                    name: 'parentId',
                    description: '父级菜单ID',
                    required: false,
                    type: 'integer',
                    subType: null,
                    properties: null,
                  },
                  {
                    name: 'seq',
                    description: '菜单排序',
                    required: false,
                    type: 'integer',
                    subType: null,
                    properties: null,
                  },
                  {
                    name: 'permissionName',
                    description: '菜单标题',
                    required: false,
                    type: 'string',
                    subType: null,
                    properties: null,
                  },
                ],
              },
            ],
          },
          {
            name: 'timestamp',
            required: false,
            type: 'integer',
            subType: null,
            properties: null,
          },
          {
            name: 'username',
            description: '用户名称',
            required: false,
            type: 'string',
            subType: null,
            properties: null,
          },
        ],
      },
      {
        name: 'success',
        description: '业务响应是否成功',
        required: false,
        type: 'boolean',
        subType: null,
        properties: null,
      },
      {
        name: 'message',
        description: '业务响应信息',
        required: false,
        type: 'string',
        subType: null,
        properties: null,
      },
    ],
    tags: ['V1.0.0-用户信息', '用户信息'],
  },
  config: { comment: false, tsNotStrict: false },
  expectResult: {
    code: '{code?:number,data?:DataVO,success?:boolean,message?:string}',
    models: [
      {
        name: 'DataVO',
        value: {
          'deviceType?': 'number',
          'orgDptInfoList?': 'Array<OrgDptInfoListVO>',
          'orgName?': 'string',
          'dptId?': 'number',
          'dptName?': 'string',
          'loginName?': 'string',
          'photo?': 'string',
          'userId?': 'number',
          'orgId?': 'number',
          'permissionInfo?': 'PermissionInfoVO',
          'timestamp?': 'number',
          'username?': 'string',
        },
      },
      { name: 'OrgDptInfoListVO', value: 'any' },
      {
        name: 'PermissionInfoVO',
        value: { 'menuList?': 'Array<MenuListVO>' },
      },
      {
        name: 'MenuListVO',
        value: {
          'hideInMenu?': 'boolean',
          'permissionType?': 'number',
          'subMenuList?': 'Array<MenuListVO>',
          'componentPath?': 'string',
          'perms?': 'string',
          'id?': 'number',
          'extraAttrs?': 'string',
          'isDisplay?': 'boolean',
          'parentId?': 'number',
          'seq?': 'number',
          'permissionName?': 'string',
        },
      },
    ],
  },
};

// 模拟同名dto场景
const case6 = {
  inputData: {
    id: 'getUserInfoUsingGET',
    path: '/auth/m/user/getUserInfo',
    title: '获取用户信息',
    method: 'get',
    query: null,
    body: null,
    response: [
      {
        name: 'code',
        description: '业务响应状态码',
        required: false,
        type: 'integer',
        subType: null,
        properties: null,
      },
      {
        name: 'data',
        description: '业务响应数据',
        required: false,
        subTypes: null,
        properties: [
          {
            name: 'orgDptInfoList',
            description: '父级部门ID',
            required: false,
            type: 'array',
            subTypes: null,
            properties: [
              {
                name: 'menuList',
                description: '子菜单列表',
                required: false,
                type: 'array',
                subTypes: null,
                properties: [
                  {
                    name: 'hideInMenu',
                    description: '菜单是否隐藏',
                    required: false,
                    type: 'boolean',
                    subType: null,
                    properties: null,
                  },
                ],
              },
            ],
          },
          {
            name: 'list',
            description: '父级部门ID',
            required: false,
            type: 'array',
            subTypes: null,
            properties: [
              {
                name: 'menuList',
                description: '子菜单列表',
                required: false,
                type: 'array',
                subTypes: null,
                properties: [
                  {
                    name: 'hideInMenu1',
                    description: '菜单是否隐藏',
                    required: false,
                    type: 'boolean',
                    subType: null,
                    properties: null,
                  },
                ],
              },
            ],
          },
          {
            name: 'permissionInfo',
            description: '权限列表（包含按钮）',
            required: false,
            subTypes: null,
            properties: [
              {
                name: 'menuList',
                description: '功能菜单列表',
                required: false,
                type: 'array',
                subTypes: null,
                properties: [
                  {
                    name: 'permissionType',
                    description: '类型 1：菜单 2：按钮',
                    required: false,
                    type: 'integer',
                    subType: null,
                    properties: null,
                  },
                  {
                    name: 'menuList',
                    description: '子菜单列表',
                    required: false,
                    type: 'array',
                    subTypes: null,
                    properties: [

                      {
                        name: 'componentPath',
                        description: '菜单路由',
                        required: false,
                        type: 'string',
                        subType: null,
                        properties: null,
                      },

                    ],
                  },
                ],
              },
            ],
          },
        ],
      },
      {
        name: 'success',
        description: '业务响应是否成功',
        required: false,
        type: 'boolean',
        subType: null,
        properties: null,
      },
      {
        name: 'message',
        description: '业务响应信息',
        required: false,
        type: 'string',
        subType: null,
        properties: null,
      },
    ],
    tags: ['V1.0.0-用户信息', '用户信息'],
  },
  config: { comment: false, tsNotStrict: false },
  expectResult: {
    code: '{code?:number,data?:DataVO,success?:boolean,message?:string}',
    models: [
      {
        name: 'DataVO',
        value: {
          'orgDptInfoList?': 'Array<OrgDptInfoListVO>',
          'list?': 'Array<ListVO>',
          'permissionInfo?': 'PermissionInfoVO',
        },
      },
      {
        name: 'OrgDptInfoListVO',
        value: { 'menuList?': 'Array<MenuListVO>' },
      },
      {
        name: 'ListVO',
        value: { 'menuList?': 'Array<MenuListAVO>' },
      },
      {
        name: 'PermissionInfoVO',
        value: { 'menuList?': 'Array<MenuListAAVO>' },
      },
      {
        name: 'MenuListVO',
        value: {
          'hideInMenu?': 'boolean',
        },
      },
      {
        name: 'MenuListAVO',
        value: {
          'hideInMenu1?': 'boolean',
        },
      },
      {
        name: 'MenuListAAVO',
        value: {
          'permissionType?': 'number',
          'menuList?': 'Array<MenuListVODto>',
        },
      },
      {
        name: 'MenuListVODto',
        value: {
          'componentPath?': 'string',
        },
      },
    ],
  },
};

const case7 = {
  inputData: { response: null },
  config: { comment: false, tsNotStrict: false },
  expectResult: {
    code: null,
    models: [],
  },
};

module.exports = {
  case1,
  case2,
  case3,
  case4,
  case5,
  case6,
  case7,
};
